import "./globals.css"
import { AuthProvider } from "../context/AuthContext"
import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"
import { ThemeProvider } from "@/context/ThemeContext"
import MainLayout from "@/layouts/MainLayout"
import StyledComponentsRegistry from "@/lib/registry"
import { inter } from "@/styles/fonts"

export const metadata = {
  title: "Front Enders' Blog",
  description: "Generated by create next app",
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <StyledComponentsRegistry>
            <ThemeProvider>
              <Navbar />
              <MainLayout>{children}</MainLayout>
              <Footer />
            </ThemeProvider>
          </StyledComponentsRegistry>
        </AuthProvider>
      </body>
    </html>
  )
}

export default RootLayout
