import "./globals.css"
import { ThemeProvider } from "@/context/ThemeContext"
import StyledComponentsRegistry from "@/lib/registry"
import { inter } from "@/styles/fonts"

export const metadata = {
  title: "Front Enders' Blog",
  description: "Generated by create next app",
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ThemeProvider>{children}</ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}

export default RootLayout
